controller_list:
  - name: fake_indy7_controller
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
initial:  # Define initial robot poses.
  - group: indy7
    pose: zero_pos