topic_list:
    - name: indy7_controller
      ns: sda10f
      group: 1
      joints: ['joint0','joint1','joint2','joint3','joint4','joint5']
    - name: irb120_controller
      ns: sda10f
      group: 2
      joints: ['joint_1','joint_2','joint_3','joint_4','joint_5','joint_6']

