controller_list:
  - name: fake_irb120_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses.
  - group: irb120
    pose: zero_pos